import type { Metadata } from "next";
import "./globals.css";
import clashGrotesk from 'next/font/local';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const myFont = clashGrotesk({
    src: '../../public/fonts/ClashGrotesk-Regular.ttf',
            
})

export default function RootLayout(
    {children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={myFont.className}>{children}</body>
        </html>
    );
}